name: petani_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  better_player: ^0.0.82
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_login: ^3.1.0
  flutter_svg: ^1.1.0
  form_field_validator: ^1.1.0
  get: 4.6.1
  get_storage: ^2.0.3
  getwidget: ^2.0.4
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  video_thumbnail: ^0.5.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  image_path: "assets/icons/logo.png"
  android: true
  ios: true
